image: Visual Studio 2017
version: 1.0.{build}
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- cmd: nuget restore
environment:
  CODECOV_REPO_TOKEN:
    secure: QTCcL5PO5FwcXfhi5ghbpgn3DS0eatZtTnBPOfcjbnvT33yxC025LtcoGdwbTVy3
configuration:
  - Release
test_script:
  - nuget install OpenCover -OutputDirectory packages -Version 4.6.519
  - .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -target:"dotnet.exe" -targetargs:"test Quill.Delta.Test\Quill.Delta.Test.csproj --configuration Release --no-build" -filter:"+[*]* -[*.Test*]* -[nunit*]*" -excludebyattribute:"System.CodeDom.Compiler.GeneratedCodeAttribute" -skipautoprops -oldStyle -mergeoutput -register:user -output:"OpenCover.xml"
after_test:
- ps: |
    $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
    Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
    bash codecov.sh -f "OpenCover.xml" -t $env:CODECOV_REPO_TOKEN
for:
-
  branches:
    only:
      - master

  build:
    publish_nuget: true

  deploy:
    provider: NuGet
    api_key:
      secure: yWR0csSBMvGp5x4I50QTopxBojnsBkWUa2v4zRvpcO1q3di3SxYJXRX3xwXyEJ88
    skip_symbols: false
